import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import WhatsAppFloat from "../components/WhatsAppFloat";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "InteliDiet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${inter.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        {children}
        <WhatsAppFloat />
      </body>
    </html>
  );
}
